namespace Discuss.WsProtocol;

table PttDown {
  ts: ulong;
  is_repeat: bool;
}

table PttUp {
  ts: ulong;
}

table Ping {}
table Pong {
  ts: ulong;
}

table Status {
  ts: ulong;
  state: string;
  version: string;
}

table CallState {
  ts: ulong;
  has_call: bool;
  has_state: bool;
  is_mute: bool;
  is_deaf: bool;
  is_camera_on: bool;
  is_screen_on: bool;
}

table Error {
  ts: ulong;
  message: string;
}

table Shutdown {}

union MessageBody {
  Ping,
  Pong,
  PttDown,
  PttUp,
  Status,
  CallState,
  Error,
  Shutdown
}

table Message {
  body: MessageBody;
}

root_type Message;
