namespace Discuss.WsProtocol;

enum Modifier : ubyte { Shift, Control, Alt, Meta }

table KeyBinding {
  code: ushort;
  modifiers: [Modifier];
}

table PttDown {
  ts: ulong;
  key: KeyBinding;
  is_repeat: bool;
}

table PttUp {
  ts: ulong;
  key: KeyBinding;
}

table Ping {}
table Pong {
  ts: ulong;
}

table Status {
  ts: ulong;
  state: string;
  version: string;
}

table CallState {
  ts: ulong;
  has_call: bool;
  has_state: bool;
  is_mute: bool;
  is_deaf: bool;
  is_camera_on: bool;
  is_screen_on: bool;
}

table Error {
  ts: ulong;
  message: string;
}

table BindingInfo {
  ts: ulong;
  binding: KeyBinding;
}

table SetBinding {
  binding: KeyBinding;
}

table GetBinding {}

table Shutdown {}

union MessageBody {
  Ping,
  Pong,
  PttDown,
  PttUp,
  Status,
  CallState,
  Error,
  BindingInfo,
  SetBinding,
  GetBinding,
  Shutdown
}

table Message {
  body: MessageBody;
}

root_type Message;
