// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod discuss {

#[allow(unused_imports, dead_code)]
pub mod ipc_protocol {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MODIFIER: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MODIFIER: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MODIFIER: [Modifier; 4] = [
  Modifier::Shift,
  Modifier::Control,
  Modifier::Alt,
  Modifier::Meta,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Modifier(pub u8);
#[allow(non_upper_case_globals)]
impl Modifier {
  pub const Shift: Self = Self(0);
  pub const Control: Self = Self(1);
  pub const Alt: Self = Self(2);
  pub const Meta: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Shift,
    Self::Control,
    Self::Alt,
    Self::Meta,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Shift => Some("Shift"),
      Self::Control => Some("Control"),
      Self::Alt => Some("Alt"),
      Self::Meta => Some("Meta"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Modifier {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Modifier {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Modifier {
    type Output = Modifier;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Modifier {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Modifier {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Modifier {}
pub enum PttBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PttBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PttBinding<'a> {
  type Inner = PttBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PttBinding<'a> {
  pub const VT_CODE: ::flatbuffers::VOffsetT = 4;
  pub const VT_MODIFIERS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PttBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PttBindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PttBinding<'bldr>> {
    let mut builder = PttBindingBuilder::new(_fbb);
    if let Some(x) = args.modifiers { builder.add_modifiers(x); }
    builder.add_code(args.code);
    builder.finish()
  }


  #[inline]
  pub fn code(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(PttBinding::VT_CODE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn modifiers(&self) -> Option<::flatbuffers::Vector<'a, Modifier>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, Modifier>>>(PttBinding::VT_MODIFIERS, None)}
  }
}

impl ::flatbuffers::Verifiable for PttBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("code", Self::VT_CODE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, Modifier>>>("modifiers", Self::VT_MODIFIERS, false)?
     .finish();
    Ok(())
  }
}
pub struct PttBindingArgs<'a> {
    pub code: u16,
    pub modifiers: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, Modifier>>>,
}
impl<'a> Default for PttBindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    PttBindingArgs {
      code: 0,
      modifiers: None,
    }
  }
}

pub struct PttBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PttBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_code(&mut self, code: u16) {
    self.fbb_.push_slot::<u16>(PttBinding::VT_CODE, code, 0);
  }
  #[inline]
  pub fn add_modifiers(&mut self, modifiers: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , Modifier>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(PttBinding::VT_MODIFIERS, modifiers);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PttBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PttBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PttBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PttBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PttBinding");
      ds.field("code", &self.code());
      ds.field("modifiers", &self.modifiers());
      ds.finish()
  }
}
pub enum SetRecordingModeOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SetRecordingMode<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SetRecordingMode<'a> {
  type Inner = SetRecordingMode<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SetRecordingMode<'a> {
  pub const VT_RECORDING: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SetRecordingMode { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SetRecordingModeArgs
  ) -> ::flatbuffers::WIPOffset<SetRecordingMode<'bldr>> {
    let mut builder = SetRecordingModeBuilder::new(_fbb);
    builder.add_recording(args.recording);
    builder.finish()
  }


  #[inline]
  pub fn recording(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(SetRecordingMode::VT_RECORDING, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SetRecordingMode<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<bool>("recording", Self::VT_RECORDING, false)?
     .finish();
    Ok(())
  }
}
pub struct SetRecordingModeArgs {
    pub recording: bool,
}
impl<'a> Default for SetRecordingModeArgs {
  #[inline]
  fn default() -> Self {
    SetRecordingModeArgs {
      recording: false,
    }
  }
}

pub struct SetRecordingModeBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SetRecordingModeBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_recording(&mut self, recording: bool) {
    self.fbb_.push_slot::<bool>(SetRecordingMode::VT_RECORDING, recording, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SetRecordingModeBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SetRecordingModeBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SetRecordingMode<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SetRecordingMode<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SetRecordingMode");
      ds.field("recording", &self.recording());
      ds.finish()
  }
}
pub enum SetWsPortOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SetWsPort<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SetWsPort<'a> {
  type Inner = SetWsPort<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SetWsPort<'a> {
  pub const VT_PORT: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SetWsPort { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SetWsPortArgs
  ) -> ::flatbuffers::WIPOffset<SetWsPort<'bldr>> {
    let mut builder = SetWsPortBuilder::new(_fbb);
    builder.add_port(args.port);
    builder.finish()
  }


  #[inline]
  pub fn port(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(SetWsPort::VT_PORT, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for SetWsPort<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("port", Self::VT_PORT, false)?
     .finish();
    Ok(())
  }
}
pub struct SetWsPortArgs {
    pub port: u16,
}
impl<'a> Default for SetWsPortArgs {
  #[inline]
  fn default() -> Self {
    SetWsPortArgs {
      port: 0,
    }
  }
}

pub struct SetWsPortBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SetWsPortBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_port(&mut self, port: u16) {
    self.fbb_.push_slot::<u16>(SetWsPort::VT_PORT, port, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SetWsPortBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SetWsPortBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SetWsPort<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SetWsPort<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SetWsPort");
      ds.field("port", &self.port());
      ds.finish()
  }
}
}  // pub mod IpcProtocol
}  // pub mod Discuss

