// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;


#[allow(unused_imports, dead_code)]
pub mod discuss {

#[allow(unused_imports, dead_code)]
pub mod ws_protocol {


#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MODIFIER: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MODIFIER: u8 = 3;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MODIFIER: [Modifier; 4] = [
  Modifier::Shift,
  Modifier::Control,
  Modifier::Alt,
  Modifier::Meta,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct Modifier(pub u8);
#[allow(non_upper_case_globals)]
impl Modifier {
  pub const Shift: Self = Self(0);
  pub const Control: Self = Self(1);
  pub const Alt: Self = Self(2);
  pub const Meta: Self = Self(3);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 3;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::Shift,
    Self::Control,
    Self::Alt,
    Self::Meta,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::Shift => Some("Shift"),
      Self::Control => Some("Control"),
      Self::Alt => Some("Alt"),
      Self::Meta => Some("Meta"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for Modifier {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for Modifier {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for Modifier {
    type Output = Modifier;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for Modifier {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for Modifier {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for Modifier {}
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MIN_MESSAGE_BODY: u8 = 0;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
pub const ENUM_MAX_MESSAGE_BODY: u8 = 11;
#[deprecated(since = "2.0.0", note = "Use associated constants instead. This will no longer be generated in 2021.")]
#[allow(non_camel_case_types)]
pub const ENUM_VALUES_MESSAGE_BODY: [MessageBody; 12] = [
  MessageBody::NONE,
  MessageBody::Ping,
  MessageBody::Pong,
  MessageBody::PttDown,
  MessageBody::PttUp,
  MessageBody::Status,
  MessageBody::CallState,
  MessageBody::Error,
  MessageBody::BindingInfo,
  MessageBody::SetBinding,
  MessageBody::GetBinding,
  MessageBody::Shutdown,
];

#[derive(Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash, Default)]
#[repr(transparent)]
pub struct MessageBody(pub u8);
#[allow(non_upper_case_globals)]
impl MessageBody {
  pub const NONE: Self = Self(0);
  pub const Ping: Self = Self(1);
  pub const Pong: Self = Self(2);
  pub const PttDown: Self = Self(3);
  pub const PttUp: Self = Self(4);
  pub const Status: Self = Self(5);
  pub const CallState: Self = Self(6);
  pub const Error: Self = Self(7);
  pub const BindingInfo: Self = Self(8);
  pub const SetBinding: Self = Self(9);
  pub const GetBinding: Self = Self(10);
  pub const Shutdown: Self = Self(11);

  pub const ENUM_MIN: u8 = 0;
  pub const ENUM_MAX: u8 = 11;
  pub const ENUM_VALUES: &'static [Self] = &[
    Self::NONE,
    Self::Ping,
    Self::Pong,
    Self::PttDown,
    Self::PttUp,
    Self::Status,
    Self::CallState,
    Self::Error,
    Self::BindingInfo,
    Self::SetBinding,
    Self::GetBinding,
    Self::Shutdown,
  ];
  /// Returns the variant's name or "" if unknown.
  pub fn variant_name(self) -> Option<&'static str> {
    match self {
      Self::NONE => Some("NONE"),
      Self::Ping => Some("Ping"),
      Self::Pong => Some("Pong"),
      Self::PttDown => Some("PttDown"),
      Self::PttUp => Some("PttUp"),
      Self::Status => Some("Status"),
      Self::CallState => Some("CallState"),
      Self::Error => Some("Error"),
      Self::BindingInfo => Some("BindingInfo"),
      Self::SetBinding => Some("SetBinding"),
      Self::GetBinding => Some("GetBinding"),
      Self::Shutdown => Some("Shutdown"),
      _ => None,
    }
  }
}
impl ::core::fmt::Debug for MessageBody {
  fn fmt(&self, f: &mut ::core::fmt::Formatter) -> ::core::fmt::Result {
    if let Some(name) = self.variant_name() {
      f.write_str(name)
    } else {
      f.write_fmt(format_args!("<UNKNOWN {:?}>", self.0))
    }
  }
}
impl<'a> ::flatbuffers::Follow<'a> for MessageBody {
  type Inner = Self;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    let b = unsafe { ::flatbuffers::read_scalar_at::<u8>(buf, loc) };
    Self(b)
  }
}

impl ::flatbuffers::Push for MessageBody {
    type Output = MessageBody;
    #[inline]
    unsafe fn push(&self, dst: &mut [u8], _written_len: usize) {
        unsafe { ::flatbuffers::emplace_scalar::<u8>(dst, self.0) };
    }
}

impl ::flatbuffers::EndianScalar for MessageBody {
  type Scalar = u8;
  #[inline]
  fn to_little_endian(self) -> u8 {
    self.0.to_le()
  }
  #[inline]
  #[allow(clippy::wrong_self_convention)]
  fn from_little_endian(v: u8) -> Self {
    let b = u8::from_le(v);
    Self(b)
  }
}

impl<'a> ::flatbuffers::Verifiable for MessageBody {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    u8::run_verifier(v, pos)
  }
}

impl ::flatbuffers::SimpleToVerifyInSlice for MessageBody {}
pub struct MessageBodyUnionTableOffset {}

pub enum KeyBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct KeyBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for KeyBinding<'a> {
  type Inner = KeyBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> KeyBinding<'a> {
  pub const VT_CODE: ::flatbuffers::VOffsetT = 4;
  pub const VT_MODIFIERS: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    KeyBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args KeyBindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<KeyBinding<'bldr>> {
    let mut builder = KeyBindingBuilder::new(_fbb);
    if let Some(x) = args.modifiers { builder.add_modifiers(x); }
    builder.add_code(args.code);
    builder.finish()
  }


  #[inline]
  pub fn code(&self) -> u16 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u16>(KeyBinding::VT_CODE, Some(0)).unwrap()}
  }
  #[inline]
  pub fn modifiers(&self) -> Option<::flatbuffers::Vector<'a, Modifier>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'a, Modifier>>>(KeyBinding::VT_MODIFIERS, None)}
  }
}

impl ::flatbuffers::Verifiable for KeyBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u16>("code", Self::VT_CODE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<::flatbuffers::Vector<'_, Modifier>>>("modifiers", Self::VT_MODIFIERS, false)?
     .finish();
    Ok(())
  }
}
pub struct KeyBindingArgs<'a> {
    pub code: u16,
    pub modifiers: Option<::flatbuffers::WIPOffset<::flatbuffers::Vector<'a, Modifier>>>,
}
impl<'a> Default for KeyBindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    KeyBindingArgs {
      code: 0,
      modifiers: None,
    }
  }
}

pub struct KeyBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> KeyBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_code(&mut self, code: u16) {
    self.fbb_.push_slot::<u16>(KeyBinding::VT_CODE, code, 0);
  }
  #[inline]
  pub fn add_modifiers(&mut self, modifiers: ::flatbuffers::WIPOffset<::flatbuffers::Vector<'b , Modifier>>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(KeyBinding::VT_MODIFIERS, modifiers);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> KeyBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    KeyBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<KeyBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for KeyBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("KeyBinding");
      ds.field("code", &self.code());
      ds.field("modifiers", &self.modifiers());
      ds.finish()
  }
}
pub enum PttDownOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PttDown<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PttDown<'a> {
  type Inner = PttDown<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PttDown<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY: ::flatbuffers::VOffsetT = 6;
  pub const VT_IS_REPEAT: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PttDown { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PttDownArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PttDown<'bldr>> {
    let mut builder = PttDownBuilder::new(_fbb);
    builder.add_ts(args.ts);
    if let Some(x) = args.key { builder.add_key(x); }
    builder.add_is_repeat(args.is_repeat);
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PttDown::VT_TS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key(&self) -> Option<KeyBinding<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<KeyBinding>>(PttDown::VT_KEY, None)}
  }
  #[inline]
  pub fn is_repeat(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(PttDown::VT_IS_REPEAT, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for PttDown<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<KeyBinding>>("key", Self::VT_KEY, false)?
     .visit_field::<bool>("is_repeat", Self::VT_IS_REPEAT, false)?
     .finish();
    Ok(())
  }
}
pub struct PttDownArgs<'a> {
    pub ts: u64,
    pub key: Option<::flatbuffers::WIPOffset<KeyBinding<'a>>>,
    pub is_repeat: bool,
}
impl<'a> Default for PttDownArgs<'a> {
  #[inline]
  fn default() -> Self {
    PttDownArgs {
      ts: 0,
      key: None,
      is_repeat: false,
    }
  }
}

pub struct PttDownBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PttDownBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(PttDown::VT_TS, ts, 0);
  }
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<KeyBinding<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<KeyBinding>>(PttDown::VT_KEY, key);
  }
  #[inline]
  pub fn add_is_repeat(&mut self, is_repeat: bool) {
    self.fbb_.push_slot::<bool>(PttDown::VT_IS_REPEAT, is_repeat, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PttDownBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PttDownBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PttDown<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PttDown<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PttDown");
      ds.field("ts", &self.ts());
      ds.field("key", &self.key());
      ds.field("is_repeat", &self.is_repeat());
      ds.finish()
  }
}
pub enum PttUpOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct PttUp<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for PttUp<'a> {
  type Inner = PttUp<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> PttUp<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;
  pub const VT_KEY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    PttUp { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PttUpArgs<'args>
  ) -> ::flatbuffers::WIPOffset<PttUp<'bldr>> {
    let mut builder = PttUpBuilder::new(_fbb);
    builder.add_ts(args.ts);
    if let Some(x) = args.key { builder.add_key(x); }
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(PttUp::VT_TS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn key(&self) -> Option<KeyBinding<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<KeyBinding>>(PttUp::VT_KEY, None)}
  }
}

impl ::flatbuffers::Verifiable for PttUp<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<KeyBinding>>("key", Self::VT_KEY, false)?
     .finish();
    Ok(())
  }
}
pub struct PttUpArgs<'a> {
    pub ts: u64,
    pub key: Option<::flatbuffers::WIPOffset<KeyBinding<'a>>>,
}
impl<'a> Default for PttUpArgs<'a> {
  #[inline]
  fn default() -> Self {
    PttUpArgs {
      ts: 0,
      key: None,
    }
  }
}

pub struct PttUpBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PttUpBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(PttUp::VT_TS, ts, 0);
  }
  #[inline]
  pub fn add_key(&mut self, key: ::flatbuffers::WIPOffset<KeyBinding<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<KeyBinding>>(PttUp::VT_KEY, key);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PttUpBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PttUpBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<PttUp<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for PttUp<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("PttUp");
      ds.field("ts", &self.ts());
      ds.field("key", &self.key());
      ds.finish()
  }
}
pub enum PingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Ping<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Ping<'a> {
  type Inner = Ping<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Ping<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Ping { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args PingArgs
  ) -> ::flatbuffers::WIPOffset<Ping<'bldr>> {
    let mut builder = PingBuilder::new(_fbb);
    builder.finish()
  }

}

impl ::flatbuffers::Verifiable for Ping<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct PingArgs {
}
impl<'a> Default for PingArgs {
  #[inline]
  fn default() -> Self {
    PingArgs {
    }
  }
}

pub struct PingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PingBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Ping<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Ping<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Ping");
      ds.finish()
  }
}
pub enum PongOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Pong<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Pong<'a> {
  type Inner = Pong<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Pong<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Pong { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args PongArgs
  ) -> ::flatbuffers::WIPOffset<Pong<'bldr>> {
    let mut builder = PongBuilder::new(_fbb);
    builder.add_ts(args.ts);
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Pong::VT_TS, Some(0)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for Pong<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .finish();
    Ok(())
  }
}
pub struct PongArgs {
    pub ts: u64,
}
impl<'a> Default for PongArgs {
  #[inline]
  fn default() -> Self {
    PongArgs {
      ts: 0,
    }
  }
}

pub struct PongBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> PongBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(Pong::VT_TS, ts, 0);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> PongBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    PongBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Pong<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Pong<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Pong");
      ds.field("ts", &self.ts());
      ds.finish()
  }
}
pub enum StatusOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Status<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Status<'a> {
  type Inner = Status<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Status<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;
  pub const VT_STATE: ::flatbuffers::VOffsetT = 6;
  pub const VT_VERSION: ::flatbuffers::VOffsetT = 8;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Status { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args StatusArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Status<'bldr>> {
    let mut builder = StatusBuilder::new(_fbb);
    builder.add_ts(args.ts);
    if let Some(x) = args.version { builder.add_version(x); }
    if let Some(x) = args.state { builder.add_state(x); }
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Status::VT_TS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn state(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_STATE, None)}
  }
  #[inline]
  pub fn version(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Status::VT_VERSION, None)}
  }
}

impl ::flatbuffers::Verifiable for Status<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("state", Self::VT_STATE, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("version", Self::VT_VERSION, false)?
     .finish();
    Ok(())
  }
}
pub struct StatusArgs<'a> {
    pub ts: u64,
    pub state: Option<::flatbuffers::WIPOffset<&'a str>>,
    pub version: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for StatusArgs<'a> {
  #[inline]
  fn default() -> Self {
    StatusArgs {
      ts: 0,
      state: None,
      version: None,
    }
  }
}

pub struct StatusBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> StatusBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(Status::VT_TS, ts, 0);
  }
  #[inline]
  pub fn add_state(&mut self, state: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_STATE, state);
  }
  #[inline]
  pub fn add_version(&mut self, version: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Status::VT_VERSION, version);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> StatusBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    StatusBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Status<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Status<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Status");
      ds.field("ts", &self.ts());
      ds.field("state", &self.state());
      ds.field("version", &self.version());
      ds.finish()
  }
}
pub enum CallStateOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct CallState<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for CallState<'a> {
  type Inner = CallState<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> CallState<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;
  pub const VT_HAS_CALL: ::flatbuffers::VOffsetT = 6;
  pub const VT_HAS_STATE: ::flatbuffers::VOffsetT = 8;
  pub const VT_IS_MUTE: ::flatbuffers::VOffsetT = 10;
  pub const VT_IS_DEAF: ::flatbuffers::VOffsetT = 12;
  pub const VT_IS_CAMERA_ON: ::flatbuffers::VOffsetT = 14;
  pub const VT_IS_SCREEN_ON: ::flatbuffers::VOffsetT = 16;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    CallState { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args CallStateArgs
  ) -> ::flatbuffers::WIPOffset<CallState<'bldr>> {
    let mut builder = CallStateBuilder::new(_fbb);
    builder.add_ts(args.ts);
    builder.add_is_screen_on(args.is_screen_on);
    builder.add_is_camera_on(args.is_camera_on);
    builder.add_is_deaf(args.is_deaf);
    builder.add_is_mute(args.is_mute);
    builder.add_has_state(args.has_state);
    builder.add_has_call(args.has_call);
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(CallState::VT_TS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn has_call(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CallState::VT_HAS_CALL, Some(false)).unwrap()}
  }
  #[inline]
  pub fn has_state(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CallState::VT_HAS_STATE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_mute(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CallState::VT_IS_MUTE, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_deaf(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CallState::VT_IS_DEAF, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_camera_on(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CallState::VT_IS_CAMERA_ON, Some(false)).unwrap()}
  }
  #[inline]
  pub fn is_screen_on(&self) -> bool {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<bool>(CallState::VT_IS_SCREEN_ON, Some(false)).unwrap()}
  }
}

impl ::flatbuffers::Verifiable for CallState<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .visit_field::<bool>("has_call", Self::VT_HAS_CALL, false)?
     .visit_field::<bool>("has_state", Self::VT_HAS_STATE, false)?
     .visit_field::<bool>("is_mute", Self::VT_IS_MUTE, false)?
     .visit_field::<bool>("is_deaf", Self::VT_IS_DEAF, false)?
     .visit_field::<bool>("is_camera_on", Self::VT_IS_CAMERA_ON, false)?
     .visit_field::<bool>("is_screen_on", Self::VT_IS_SCREEN_ON, false)?
     .finish();
    Ok(())
  }
}
pub struct CallStateArgs {
    pub ts: u64,
    pub has_call: bool,
    pub has_state: bool,
    pub is_mute: bool,
    pub is_deaf: bool,
    pub is_camera_on: bool,
    pub is_screen_on: bool,
}
impl<'a> Default for CallStateArgs {
  #[inline]
  fn default() -> Self {
    CallStateArgs {
      ts: 0,
      has_call: false,
      has_state: false,
      is_mute: false,
      is_deaf: false,
      is_camera_on: false,
      is_screen_on: false,
    }
  }
}

pub struct CallStateBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> CallStateBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(CallState::VT_TS, ts, 0);
  }
  #[inline]
  pub fn add_has_call(&mut self, has_call: bool) {
    self.fbb_.push_slot::<bool>(CallState::VT_HAS_CALL, has_call, false);
  }
  #[inline]
  pub fn add_has_state(&mut self, has_state: bool) {
    self.fbb_.push_slot::<bool>(CallState::VT_HAS_STATE, has_state, false);
  }
  #[inline]
  pub fn add_is_mute(&mut self, is_mute: bool) {
    self.fbb_.push_slot::<bool>(CallState::VT_IS_MUTE, is_mute, false);
  }
  #[inline]
  pub fn add_is_deaf(&mut self, is_deaf: bool) {
    self.fbb_.push_slot::<bool>(CallState::VT_IS_DEAF, is_deaf, false);
  }
  #[inline]
  pub fn add_is_camera_on(&mut self, is_camera_on: bool) {
    self.fbb_.push_slot::<bool>(CallState::VT_IS_CAMERA_ON, is_camera_on, false);
  }
  #[inline]
  pub fn add_is_screen_on(&mut self, is_screen_on: bool) {
    self.fbb_.push_slot::<bool>(CallState::VT_IS_SCREEN_ON, is_screen_on, false);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> CallStateBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    CallStateBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<CallState<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for CallState<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("CallState");
      ds.field("ts", &self.ts());
      ds.field("has_call", &self.has_call());
      ds.field("has_state", &self.has_state());
      ds.field("is_mute", &self.is_mute());
      ds.field("is_deaf", &self.is_deaf());
      ds.field("is_camera_on", &self.is_camera_on());
      ds.field("is_screen_on", &self.is_screen_on());
      ds.finish()
  }
}
pub enum ErrorOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Error<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Error<'a> {
  type Inner = Error<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Error<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;
  pub const VT_MESSAGE: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Error { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args ErrorArgs<'args>
  ) -> ::flatbuffers::WIPOffset<Error<'bldr>> {
    let mut builder = ErrorBuilder::new(_fbb);
    builder.add_ts(args.ts);
    if let Some(x) = args.message { builder.add_message(x); }
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(Error::VT_TS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn message(&self) -> Option<&'a str> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<&str>>(Error::VT_MESSAGE, None)}
  }
}

impl ::flatbuffers::Verifiable for Error<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<&str>>("message", Self::VT_MESSAGE, false)?
     .finish();
    Ok(())
  }
}
pub struct ErrorArgs<'a> {
    pub ts: u64,
    pub message: Option<::flatbuffers::WIPOffset<&'a str>>,
}
impl<'a> Default for ErrorArgs<'a> {
  #[inline]
  fn default() -> Self {
    ErrorArgs {
      ts: 0,
      message: None,
    }
  }
}

pub struct ErrorBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ErrorBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(Error::VT_TS, ts, 0);
  }
  #[inline]
  pub fn add_message(&mut self, message: ::flatbuffers::WIPOffset<&'b  str>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Error::VT_MESSAGE, message);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ErrorBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ErrorBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Error<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Error<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Error");
      ds.field("ts", &self.ts());
      ds.field("message", &self.message());
      ds.finish()
  }
}
pub enum BindingInfoOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct BindingInfo<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for BindingInfo<'a> {
  type Inner = BindingInfo<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> BindingInfo<'a> {
  pub const VT_TS: ::flatbuffers::VOffsetT = 4;
  pub const VT_BINDING: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    BindingInfo { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args BindingInfoArgs<'args>
  ) -> ::flatbuffers::WIPOffset<BindingInfo<'bldr>> {
    let mut builder = BindingInfoBuilder::new(_fbb);
    builder.add_ts(args.ts);
    if let Some(x) = args.binding { builder.add_binding(x); }
    builder.finish()
  }


  #[inline]
  pub fn ts(&self) -> u64 {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<u64>(BindingInfo::VT_TS, Some(0)).unwrap()}
  }
  #[inline]
  pub fn binding(&self) -> Option<KeyBinding<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<KeyBinding>>(BindingInfo::VT_BINDING, None)}
  }
}

impl ::flatbuffers::Verifiable for BindingInfo<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<u64>("ts", Self::VT_TS, false)?
     .visit_field::<::flatbuffers::ForwardsUOffset<KeyBinding>>("binding", Self::VT_BINDING, false)?
     .finish();
    Ok(())
  }
}
pub struct BindingInfoArgs<'a> {
    pub ts: u64,
    pub binding: Option<::flatbuffers::WIPOffset<KeyBinding<'a>>>,
}
impl<'a> Default for BindingInfoArgs<'a> {
  #[inline]
  fn default() -> Self {
    BindingInfoArgs {
      ts: 0,
      binding: None,
    }
  }
}

pub struct BindingInfoBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> BindingInfoBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_ts(&mut self, ts: u64) {
    self.fbb_.push_slot::<u64>(BindingInfo::VT_TS, ts, 0);
  }
  #[inline]
  pub fn add_binding(&mut self, binding: ::flatbuffers::WIPOffset<KeyBinding<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<KeyBinding>>(BindingInfo::VT_BINDING, binding);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> BindingInfoBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    BindingInfoBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<BindingInfo<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for BindingInfo<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("BindingInfo");
      ds.field("ts", &self.ts());
      ds.field("binding", &self.binding());
      ds.finish()
  }
}
pub enum SetBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct SetBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for SetBinding<'a> {
  type Inner = SetBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> SetBinding<'a> {
  pub const VT_BINDING: ::flatbuffers::VOffsetT = 4;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    SetBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args SetBindingArgs<'args>
  ) -> ::flatbuffers::WIPOffset<SetBinding<'bldr>> {
    let mut builder = SetBindingBuilder::new(_fbb);
    if let Some(x) = args.binding { builder.add_binding(x); }
    builder.finish()
  }


  #[inline]
  pub fn binding(&self) -> Option<KeyBinding<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<KeyBinding>>(SetBinding::VT_BINDING, None)}
  }
}

impl ::flatbuffers::Verifiable for SetBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_field::<::flatbuffers::ForwardsUOffset<KeyBinding>>("binding", Self::VT_BINDING, false)?
     .finish();
    Ok(())
  }
}
pub struct SetBindingArgs<'a> {
    pub binding: Option<::flatbuffers::WIPOffset<KeyBinding<'a>>>,
}
impl<'a> Default for SetBindingArgs<'a> {
  #[inline]
  fn default() -> Self {
    SetBindingArgs {
      binding: None,
    }
  }
}

pub struct SetBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> SetBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_binding(&mut self, binding: ::flatbuffers::WIPOffset<KeyBinding<'b >>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<KeyBinding>>(SetBinding::VT_BINDING, binding);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> SetBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    SetBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<SetBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for SetBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("SetBinding");
      ds.field("binding", &self.binding());
      ds.finish()
  }
}
pub enum GetBindingOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct GetBinding<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for GetBinding<'a> {
  type Inner = GetBinding<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> GetBinding<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    GetBinding { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args GetBindingArgs
  ) -> ::flatbuffers::WIPOffset<GetBinding<'bldr>> {
    let mut builder = GetBindingBuilder::new(_fbb);
    builder.finish()
  }

}

impl ::flatbuffers::Verifiable for GetBinding<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct GetBindingArgs {
}
impl<'a> Default for GetBindingArgs {
  #[inline]
  fn default() -> Self {
    GetBindingArgs {
    }
  }
}

pub struct GetBindingBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> GetBindingBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> GetBindingBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    GetBindingBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<GetBinding<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for GetBinding<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("GetBinding");
      ds.finish()
  }
}
pub enum ShutdownOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Shutdown<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Shutdown<'a> {
  type Inner = Shutdown<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Shutdown<'a> {

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Shutdown { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    _args: &'args ShutdownArgs
  ) -> ::flatbuffers::WIPOffset<Shutdown<'bldr>> {
    let mut builder = ShutdownBuilder::new(_fbb);
    builder.finish()
  }

}

impl ::flatbuffers::Verifiable for Shutdown<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .finish();
    Ok(())
  }
}
pub struct ShutdownArgs {
}
impl<'a> Default for ShutdownArgs {
  #[inline]
  fn default() -> Self {
    ShutdownArgs {
    }
  }
}

pub struct ShutdownBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> ShutdownBuilder<'a, 'b, A> {
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> ShutdownBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    ShutdownBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Shutdown<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Shutdown<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Shutdown");
      ds.finish()
  }
}
pub enum MessageOffset {}
#[derive(Copy, Clone, PartialEq)]

pub struct Message<'a> {
  pub _tab: ::flatbuffers::Table<'a>,
}

impl<'a> ::flatbuffers::Follow<'a> for Message<'a> {
  type Inner = Message<'a>;
  #[inline]
  unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
    Self { _tab: unsafe { ::flatbuffers::Table::new(buf, loc) } }
  }
}

impl<'a> Message<'a> {
  pub const VT_BODY_TYPE: ::flatbuffers::VOffsetT = 4;
  pub const VT_BODY: ::flatbuffers::VOffsetT = 6;

  #[inline]
  pub unsafe fn init_from_table(table: ::flatbuffers::Table<'a>) -> Self {
    Message { _tab: table }
  }
  #[allow(unused_mut)]
  pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr, A: ::flatbuffers::Allocator + 'bldr>(
    _fbb: &'mut_bldr mut ::flatbuffers::FlatBufferBuilder<'bldr, A>,
    args: &'args MessageArgs
  ) -> ::flatbuffers::WIPOffset<Message<'bldr>> {
    let mut builder = MessageBuilder::new(_fbb);
    if let Some(x) = args.body { builder.add_body(x); }
    builder.add_body_type(args.body_type);
    builder.finish()
  }


  #[inline]
  pub fn body_type(&self) -> MessageBody {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<MessageBody>(Message::VT_BODY_TYPE, Some(MessageBody::NONE)).unwrap()}
  }
  #[inline]
  pub fn body(&self) -> Option<::flatbuffers::Table<'a>> {
    // Safety:
    // Created from valid Table for this object
    // which contains a valid value in this slot
    unsafe { self._tab.get::<::flatbuffers::ForwardsUOffset<::flatbuffers::Table<'a>>>(Message::VT_BODY, None)}
  }
  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_ping(&self) -> Option<Ping<'a>> {
    if self.body_type() == MessageBody::Ping {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Ping::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_pong(&self) -> Option<Pong<'a>> {
    if self.body_type() == MessageBody::Pong {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Pong::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_ptt_down(&self) -> Option<PttDown<'a>> {
    if self.body_type() == MessageBody::PttDown {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PttDown::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_ptt_up(&self) -> Option<PttUp<'a>> {
    if self.body_type() == MessageBody::PttUp {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { PttUp::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_status(&self) -> Option<Status<'a>> {
    if self.body_type() == MessageBody::Status {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Status::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_call_state(&self) -> Option<CallState<'a>> {
    if self.body_type() == MessageBody::CallState {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { CallState::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_error(&self) -> Option<Error<'a>> {
    if self.body_type() == MessageBody::Error {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Error::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_binding_info(&self) -> Option<BindingInfo<'a>> {
    if self.body_type() == MessageBody::BindingInfo {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { BindingInfo::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_set_binding(&self) -> Option<SetBinding<'a>> {
    if self.body_type() == MessageBody::SetBinding {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { SetBinding::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_get_binding(&self) -> Option<GetBinding<'a>> {
    if self.body_type() == MessageBody::GetBinding {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { GetBinding::init_from_table(t) }
     })
    } else {
      None
    }
  }

  #[inline]
  #[allow(non_snake_case)]
  pub fn body_as_shutdown(&self) -> Option<Shutdown<'a>> {
    if self.body_type() == MessageBody::Shutdown {
      self.body().map(|t| {
       // Safety:
       // Created from a valid Table for this object
       // Which contains a valid union in this slot
       unsafe { Shutdown::init_from_table(t) }
     })
    } else {
      None
    }
  }

}

impl ::flatbuffers::Verifiable for Message<'_> {
  #[inline]
  fn run_verifier(
    v: &mut ::flatbuffers::Verifier, pos: usize
  ) -> Result<(), ::flatbuffers::InvalidFlatbuffer> {
    v.visit_table(pos)?
     .visit_union::<MessageBody, _>("body_type", Self::VT_BODY_TYPE, "body", Self::VT_BODY, false, |key, v, pos| {
        match key {
          MessageBody::Ping => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Ping>>("MessageBody::Ping", pos),
          MessageBody::Pong => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Pong>>("MessageBody::Pong", pos),
          MessageBody::PttDown => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<PttDown>>("MessageBody::PttDown", pos),
          MessageBody::PttUp => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<PttUp>>("MessageBody::PttUp", pos),
          MessageBody::Status => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Status>>("MessageBody::Status", pos),
          MessageBody::CallState => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<CallState>>("MessageBody::CallState", pos),
          MessageBody::Error => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Error>>("MessageBody::Error", pos),
          MessageBody::BindingInfo => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<BindingInfo>>("MessageBody::BindingInfo", pos),
          MessageBody::SetBinding => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<SetBinding>>("MessageBody::SetBinding", pos),
          MessageBody::GetBinding => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<GetBinding>>("MessageBody::GetBinding", pos),
          MessageBody::Shutdown => v.verify_union_variant::<::flatbuffers::ForwardsUOffset<Shutdown>>("MessageBody::Shutdown", pos),
          _ => Ok(()),
        }
     })?
     .finish();
    Ok(())
  }
}
pub struct MessageArgs {
    pub body_type: MessageBody,
    pub body: Option<::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>>,
}
impl<'a> Default for MessageArgs {
  #[inline]
  fn default() -> Self {
    MessageArgs {
      body_type: MessageBody::NONE,
      body: None,
    }
  }
}

pub struct MessageBuilder<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> {
  fbb_: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
  start_: ::flatbuffers::WIPOffset<::flatbuffers::TableUnfinishedWIPOffset>,
}
impl<'a: 'b, 'b, A: ::flatbuffers::Allocator + 'a> MessageBuilder<'a, 'b, A> {
  #[inline]
  pub fn add_body_type(&mut self, body_type: MessageBody) {
    self.fbb_.push_slot::<MessageBody>(Message::VT_BODY_TYPE, body_type, MessageBody::NONE);
  }
  #[inline]
  pub fn add_body(&mut self, body: ::flatbuffers::WIPOffset<::flatbuffers::UnionWIPOffset>) {
    self.fbb_.push_slot_always::<::flatbuffers::WIPOffset<_>>(Message::VT_BODY, body);
  }
  #[inline]
  pub fn new(_fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>) -> MessageBuilder<'a, 'b, A> {
    let start = _fbb.start_table();
    MessageBuilder {
      fbb_: _fbb,
      start_: start,
    }
  }
  #[inline]
  pub fn finish(self) -> ::flatbuffers::WIPOffset<Message<'a>> {
    let o = self.fbb_.end_table(self.start_);
    ::flatbuffers::WIPOffset::new(o.value())
  }
}

impl ::core::fmt::Debug for Message<'_> {
  fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
    let mut ds = f.debug_struct("Message");
      ds.field("body_type", &self.body_type());
      match self.body_type() {
        MessageBody::Ping => {
          if let Some(x) = self.body_as_ping() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::Pong => {
          if let Some(x) = self.body_as_pong() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::PttDown => {
          if let Some(x) = self.body_as_ptt_down() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::PttUp => {
          if let Some(x) = self.body_as_ptt_up() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::Status => {
          if let Some(x) = self.body_as_status() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::CallState => {
          if let Some(x) = self.body_as_call_state() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::Error => {
          if let Some(x) = self.body_as_error() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::BindingInfo => {
          if let Some(x) = self.body_as_binding_info() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::SetBinding => {
          if let Some(x) = self.body_as_set_binding() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::GetBinding => {
          if let Some(x) = self.body_as_get_binding() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        MessageBody::Shutdown => {
          if let Some(x) = self.body_as_shutdown() {
            ds.field("body", &x)
          } else {
            ds.field("body", &"InvalidFlatbuffer: Union discriminant does not match value.")
          }
        },
        _ => {
          let x: Option<()> = None;
          ds.field("body", &x)
        },
      };
      ds.finish()
  }
}
#[inline]
/// Verifies that a buffer of bytes contains a `Message`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message(buf: &[u8]) -> Result<Message<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root::<Message>(buf)
}
#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_message_unchecked`.
pub fn size_prefixed_root_as_message(buf: &[u8]) -> Result<Message<'_>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root::<Message>(buf)
}
#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `Message` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn root_as_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `Message` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_message_unchecked`.
pub fn size_prefixed_root_as_message_with_opts<'b, 'o>(
  opts: &'o ::flatbuffers::VerifierOptions,
  buf: &'b [u8],
) -> Result<Message<'b>, ::flatbuffers::InvalidFlatbuffer> {
  ::flatbuffers::size_prefixed_root_with_opts::<Message<'b>>(opts, buf)
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `Message`.
pub unsafe fn root_as_message_unchecked(buf: &[u8]) -> Message<'_> {
  unsafe { ::flatbuffers::root_unchecked::<Message>(buf) }
}
#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed Message and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `Message`.
pub unsafe fn size_prefixed_root_as_message_unchecked(buf: &[u8]) -> Message<'_> {
  unsafe { ::flatbuffers::size_prefixed_root_unchecked::<Message>(buf) }
}
#[inline]
pub fn finish_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(
    fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>,
    root: ::flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_message_buffer<'a, 'b, A: ::flatbuffers::Allocator + 'a>(fbb: &'b mut ::flatbuffers::FlatBufferBuilder<'a, A>, root: ::flatbuffers::WIPOffset<Message<'a>>) {
  fbb.finish_size_prefixed(root, None);
}
}  // pub mod WsProtocol
}  // pub mod Discuss

