[package]
authors = ["ThanhDodeurOdoo"]
description = "Odoo Discuss Companion"
edition = "2024"
name = "discuss-companion"
rust-version = "1.92"
version = "0.10.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
crate-type = ["cdylib", "rlib", "staticlib"]
name = "discuss_companion_lib"

[build-dependencies]
tauri-build = { version = "2.5", features = [] }

[dependencies]
anyhow = "1.0"
crossbeam-channel = "0.5"
flatbuffers = "25.12"
futures-util = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "2.10", features = ["image-png", "test", "tray-icon"] }
tauri-plugin-opener = "2.5"
tauri-plugin-store = "2.4"
tokio = { version = "1.49", features = ["full"] }
tokio-tungstenite = "0.28"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

# profiling
dhat = { version = "0.3.3", optional = true }

[features]
default = []
dhat-ad-hoc = ["dep:dhat"]
dhat-heap = ["dep:dhat"]
x11 = ["dep:x11"]

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = "0.10"
core-graphics = "0.25"
muda = "0.17.1"
objc2 = "0.6.3"
objc2-app-kit = { version = "0.3.2", features = ["NSApplication", "NSMenu", "NSResponder"] }

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2.180"
x11 = { version = "2.21.0", features = ["xlib", "xrecord"], optional = true }

[dev-dependencies]
serial_test = "3"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ["cfg(rust_analyzer)"] }
unsafe_code = "deny"

[lints.clippy] # https://rust-lang.github.io/rust-clippy/
correctness = { level = "deny", priority = -1 }
expect_used = { level = "deny", priority = -1 }
indexing_slicing = { level = "deny", priority = -1 }
panic = { level = "deny", priority = -1 }
suspicious = { level = "deny", priority = -1 }
unwrap_used = { level = "deny", priority = -1 }

# groups
complexity = "warn"
pedantic = "warn"
perf = "warn"
style = "warn"

absolute_paths = "warn"
allow_attributes_without_reason = "warn"
as_conversions = "warn"
as_ptr_cast_mut = "warn"
as_underscore = "warn"
assigning_clones = "warn"
clone_on_ref_ptr = "warn"
cognitive_complexity = "warn"
dbg_macro = "warn"
disallowed_script_idents = "warn"
empty_drop = "warn"
exit = "warn"
map_err_ignore = "warn"
mem_forget = "warn"
non_ascii_literal = "warn"
print_stderr = "warn"
print_stdout = "warn"
todo = "warn"
unimplemented = "warn"
unreachable = "warn"
unused_result_ok = "warn"
wildcard_dependencies = "warn"

# nursery as of rust 1.92 https://rust-lang.github.io/rust-clippy/rust-1.92.0/index.html?groups=nursery
needless_pass_by_ref_mut = "warn"
nonstandard_macro_braces = "warn"
option_if_let_else = "warn"
redundant_clone = "warn"
significant_drop_tightening = "warn"
single_option_map = "warn"
trait_duplication_in_bounds = "warn"
type_repetition_in_bounds = "warn"
uninhabited_references = "warn"
unnecessary_struct_initialization = "warn"
use_self = "warn"
useless_let_if_seq = "warn"
while_float = "warn"
