// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class GetBinding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):GetBinding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsGetBinding(bb:flatbuffers.ByteBuffer, obj?:GetBinding):GetBinding {
  return (obj || new GetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsGetBinding(bb:flatbuffers.ByteBuffer, obj?:GetBinding):GetBinding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new GetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startGetBinding(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endGetBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createGetBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  GetBinding.startGetBinding(builder);
  return GetBinding.endGetBinding(builder);
}
}
