// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class KeyBinding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):KeyBinding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsKeyBinding(bb:flatbuffers.ByteBuffer, obj?:KeyBinding):KeyBinding {
  return (obj || new KeyBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsKeyBinding(bb:flatbuffers.ByteBuffer, obj?:KeyBinding):KeyBinding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new KeyBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

modifiers(index: number):string
modifiers(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
modifiers(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

modifiersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startKeyBinding(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCode(builder:flatbuffers.Builder, code:number) {
  builder.addFieldInt16(0, code, 0);
}

static addModifiers(builder:flatbuffers.Builder, modifiersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, modifiersOffset, 0);
}

static createModifiersVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startModifiersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endKeyBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createKeyBinding(builder:flatbuffers.Builder, code:number, modifiersOffset:flatbuffers.Offset):flatbuffers.Offset {
  KeyBinding.startKeyBinding(builder);
  KeyBinding.addCode(builder, code);
  KeyBinding.addModifiers(builder, modifiersOffset);
  return KeyBinding.endKeyBinding(builder);
}
}
