// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { BindingInfo } from '../../discuss/flatbuffers/binding-info.js';
import { Error } from '../../discuss/flatbuffers/error.js';
import { GetBinding } from '../../discuss/flatbuffers/get-binding.js';
import { Ping } from '../../discuss/flatbuffers/ping.js';
import { Pong } from '../../discuss/flatbuffers/pong.js';
import { PttDown } from '../../discuss/flatbuffers/ptt-down.js';
import { PttUp } from '../../discuss/flatbuffers/ptt-up.js';
import { SetBinding } from '../../discuss/flatbuffers/set-binding.js';
import { Shutdown } from '../../discuss/flatbuffers/shutdown.js';
import { Status } from '../../discuss/flatbuffers/status.js';


export enum MessageBody {
  NONE = 0,
  Ping = 1,
  Pong = 2,
  PttDown = 3,
  PttUp = 4,
  Status = 5,
  Error = 6,
  BindingInfo = 7,
  SetBinding = 8,
  GetBinding = 9,
  Shutdown = 10
}

export function unionToMessageBody(
  type: MessageBody,
  accessor: (obj:BindingInfo|Error|GetBinding|Ping|Pong|PttDown|PttUp|SetBinding|Shutdown|Status) => BindingInfo|Error|GetBinding|Ping|Pong|PttDown|PttUp|SetBinding|Shutdown|Status|null
): BindingInfo|Error|GetBinding|Ping|Pong|PttDown|PttUp|SetBinding|Shutdown|Status|null {
  switch(MessageBody[type]) {
    case 'NONE': return null; 
    case 'Ping': return accessor(new Ping())! as Ping;
    case 'Pong': return accessor(new Pong())! as Pong;
    case 'PttDown': return accessor(new PttDown())! as PttDown;
    case 'PttUp': return accessor(new PttUp())! as PttUp;
    case 'Status': return accessor(new Status())! as Status;
    case 'Error': return accessor(new Error())! as Error;
    case 'BindingInfo': return accessor(new BindingInfo())! as BindingInfo;
    case 'SetBinding': return accessor(new SetBinding())! as SetBinding;
    case 'GetBinding': return accessor(new GetBinding())! as GetBinding;
    case 'Shutdown': return accessor(new Shutdown())! as Shutdown;
    default: return null;
  }
}

export function unionListToMessageBody(
  type: MessageBody, 
  accessor: (index: number, obj:BindingInfo|Error|GetBinding|Ping|Pong|PttDown|PttUp|SetBinding|Shutdown|Status) => BindingInfo|Error|GetBinding|Ping|Pong|PttDown|PttUp|SetBinding|Shutdown|Status|null, 
  index: number
): BindingInfo|Error|GetBinding|Ping|Pong|PttDown|PttUp|SetBinding|Shutdown|Status|null {
  switch(MessageBody[type]) {
    case 'NONE': return null; 
    case 'Ping': return accessor(index, new Ping())! as Ping;
    case 'Pong': return accessor(index, new Pong())! as Pong;
    case 'PttDown': return accessor(index, new PttDown())! as PttDown;
    case 'PttUp': return accessor(index, new PttUp())! as PttUp;
    case 'Status': return accessor(index, new Status())! as Status;
    case 'Error': return accessor(index, new Error())! as Error;
    case 'BindingInfo': return accessor(index, new BindingInfo())! as BindingInfo;
    case 'SetBinding': return accessor(index, new SetBinding())! as SetBinding;
    case 'GetBinding': return accessor(index, new GetBinding())! as GetBinding;
    case 'Shutdown': return accessor(index, new Shutdown())! as Shutdown;
    default: return null;
  }
}
