// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { KeyBinding } from '../../discuss/flatbuffers/key-binding.js';


export class SetBinding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetBinding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetBinding(bb:flatbuffers.ByteBuffer, obj?:SetBinding):SetBinding {
  return (obj || new SetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetBinding(bb:flatbuffers.ByteBuffer, obj?:SetBinding):SetBinding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

binding(obj?:KeyBinding):KeyBinding|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new KeyBinding()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startSetBinding(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBinding(builder:flatbuffers.Builder, bindingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bindingOffset, 0);
}

static endSetBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetBinding(builder:flatbuffers.Builder, bindingOffset:flatbuffers.Offset):flatbuffers.Offset {
  SetBinding.startSetBinding(builder);
  SetBinding.addBinding(builder, bindingOffset);
  return SetBinding.endSetBinding(builder);
}
}
