// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class IncomingGetBinding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IncomingGetBinding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIncomingGetBinding(bb:flatbuffers.ByteBuffer, obj?:IncomingGetBinding):IncomingGetBinding {
  return (obj || new IncomingGetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIncomingGetBinding(bb:flatbuffers.ByteBuffer, obj?:IncomingGetBinding):IncomingGetBinding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IncomingGetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startIncomingGetBinding(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endIncomingGetBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createIncomingGetBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  IncomingGetBinding.startIncomingGetBinding(builder);
  return IncomingGetBinding.endIncomingGetBinding(builder);
}
}
