// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class IncomingShutdown {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IncomingShutdown {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIncomingShutdown(bb:flatbuffers.ByteBuffer, obj?:IncomingShutdown):IncomingShutdown {
  return (obj || new IncomingShutdown()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIncomingShutdown(bb:flatbuffers.ByteBuffer, obj?:IncomingShutdown):IncomingShutdown {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IncomingShutdown()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startIncomingShutdown(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endIncomingShutdown(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createIncomingShutdown(builder:flatbuffers.Builder):flatbuffers.Offset {
  IncomingShutdown.startIncomingShutdown(builder);
  return IncomingShutdown.endIncomingShutdown(builder);
}
}
