// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { IncomingShutdown } from '../../discuss/ipc-protocol/incoming-shutdown.js';


export enum IncomingMessageUnion {
  NONE = 0,
  IncomingShutdown = 1
}

export function unionToIncomingMessageUnion(
  type: IncomingMessageUnion,
  accessor: (obj:IncomingShutdown) => IncomingShutdown|null
): IncomingShutdown|null {
  switch(IncomingMessageUnion[type]) {
    case 'NONE': return null; 
    case 'IncomingShutdown': return accessor(new IncomingShutdown())! as IncomingShutdown;
    default: return null;
  }
}

export function unionListToIncomingMessageUnion(
  type: IncomingMessageUnion, 
  accessor: (index: number, obj:IncomingShutdown) => IncomingShutdown|null, 
  index: number
): IncomingShutdown|null {
  switch(IncomingMessageUnion[type]) {
    case 'NONE': return null; 
    case 'IncomingShutdown': return accessor(index, new IncomingShutdown())! as IncomingShutdown;
    default: return null;
  }
}
