// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { PttBinding } from '../../discuss/ipc-protocol/ptt-binding.js';


export class IncomingSetBinding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):IncomingSetBinding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsIncomingSetBinding(bb:flatbuffers.ByteBuffer, obj?:IncomingSetBinding):IncomingSetBinding {
  return (obj || new IncomingSetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsIncomingSetBinding(bb:flatbuffers.ByteBuffer, obj?:IncomingSetBinding):IncomingSetBinding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new IncomingSetBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

binding(obj?:PttBinding):PttBinding|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new PttBinding()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startIncomingSetBinding(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBinding(builder:flatbuffers.Builder, bindingOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, bindingOffset, 0);
}

static endIncomingSetBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createIncomingSetBinding(builder:flatbuffers.Builder, bindingOffset:flatbuffers.Offset):flatbuffers.Offset {
  IncomingSetBinding.startIncomingSetBinding(builder);
  IncomingSetBinding.addBinding(builder, bindingOffset);
  return IncomingSetBinding.endIncomingSetBinding(builder);
}
}
