// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Modifier } from '../../discuss/ipc-protocol/modifier.js';


export class PttState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PttState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPttState(bb:flatbuffers.ByteBuffer, obj?:PttState):PttState {
  return (obj || new PttState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPttState(bb:flatbuffers.ByteBuffer, obj?:PttState):PttState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PttState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

isActive():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

code():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

modifiers(index: number):Modifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

modifiersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

modifiersArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

isRepeat():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startPttState(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addIsActive(builder:flatbuffers.Builder, isActive:boolean) {
  builder.addFieldInt8(0, +isActive, +false);
}

static addCode(builder:flatbuffers.Builder, code:number) {
  builder.addFieldInt16(1, code, 0);
}

static addModifiers(builder:flatbuffers.Builder, modifiersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(2, modifiersOffset, 0);
}

static createModifiersVector(builder:flatbuffers.Builder, data:Modifier[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startModifiersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static addIsRepeat(builder:flatbuffers.Builder, isRepeat:boolean) {
  builder.addFieldInt8(3, +isRepeat, +false);
}

static endPttState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPttState(builder:flatbuffers.Builder, isActive:boolean, code:number, modifiersOffset:flatbuffers.Offset, isRepeat:boolean):flatbuffers.Offset {
  PttState.startPttState(builder);
  PttState.addIsActive(builder, isActive);
  PttState.addCode(builder, code);
  PttState.addModifiers(builder, modifiersOffset);
  PttState.addIsRepeat(builder, isRepeat);
  return PttState.endPttState(builder);
}
}
