// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { Modifier } from '../../discuss/ipc-protocol/modifier.js';


export class PttBinding {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PttBinding {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPttBinding(bb:flatbuffers.ByteBuffer, obj?:PttBinding):PttBinding {
  return (obj || new PttBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPttBinding(bb:flatbuffers.ByteBuffer, obj?:PttBinding):PttBinding {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PttBinding()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

code():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

modifiers(index: number):Modifier|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb!.__vector(this.bb_pos + offset) + index) : null;
}

modifiersLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

modifiersArray():Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? new Uint8Array(this.bb!.bytes().buffer, this.bb!.bytes().byteOffset + this.bb!.__vector(this.bb_pos + offset), this.bb!.__vector_len(this.bb_pos + offset)) : null;
}

static startPttBinding(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addCode(builder:flatbuffers.Builder, code:number) {
  builder.addFieldInt16(0, code, 0);
}

static addModifiers(builder:flatbuffers.Builder, modifiersOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, modifiersOffset, 0);
}

static createModifiersVector(builder:flatbuffers.Builder, data:Modifier[]):flatbuffers.Offset {
  builder.startVector(1, data.length, 1);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addInt8(data[i]!);
  }
  return builder.endVector();
}

static startModifiersVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(1, numElems, 1);
}

static endPttBinding(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPttBinding(builder:flatbuffers.Builder, code:number, modifiersOffset:flatbuffers.Offset):flatbuffers.Offset {
  PttBinding.startPttBinding(builder);
  PttBinding.addCode(builder, code);
  PttBinding.addModifiers(builder, modifiersOffset);
  return PttBinding.endPttBinding(builder);
}
}
