// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SetRecordingMode {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetRecordingMode {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetRecordingMode(bb:flatbuffers.ByteBuffer, obj?:SetRecordingMode):SetRecordingMode {
  return (obj || new SetRecordingMode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetRecordingMode(bb:flatbuffers.ByteBuffer, obj?:SetRecordingMode):SetRecordingMode {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetRecordingMode()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

recording():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startSetRecordingMode(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addRecording(builder:flatbuffers.Builder, recording:boolean) {
  builder.addFieldInt8(0, +recording, +false);
}

static endSetRecordingMode(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetRecordingMode(builder:flatbuffers.Builder, recording:boolean):flatbuffers.Offset {
  SetRecordingMode.startSetRecordingMode(builder);
  SetRecordingMode.addRecording(builder, recording);
  return SetRecordingMode.endSetRecordingMode(builder);
}
}
