// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class SetWsPort {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):SetWsPort {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsSetWsPort(bb:flatbuffers.ByteBuffer, obj?:SetWsPort):SetWsPort {
  return (obj || new SetWsPort()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsSetWsPort(bb:flatbuffers.ByteBuffer, obj?:SetWsPort):SetWsPort {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new SetWsPort()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

port():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint16(this.bb_pos + offset) : 0;
}

static startSetWsPort(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addPort(builder:flatbuffers.Builder, port:number) {
  builder.addFieldInt16(0, port, 0);
}

static endSetWsPort(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createSetWsPort(builder:flatbuffers.Builder, port:number):flatbuffers.Offset {
  SetWsPort.startSetWsPort(builder);
  SetWsPort.addPort(builder, port);
  return SetWsPort.endSetWsPort(builder);
}
}
