// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ToFrontend, unionToToFrontend, unionListToToFrontend } from '../../discuss/ipc-protocol/to-frontend.js';


export class ToFrontendMessage {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ToFrontendMessage {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsToFrontendMessage(bb:flatbuffers.ByteBuffer, obj?:ToFrontendMessage):ToFrontendMessage {
  return (obj || new ToFrontendMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsToFrontendMessage(bb:flatbuffers.ByteBuffer, obj?:ToFrontendMessage):ToFrontendMessage {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ToFrontendMessage()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

eventType():ToFrontend {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ToFrontend.NONE;
}

event<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startToFrontendMessage(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addEventType(builder:flatbuffers.Builder, eventType:ToFrontend) {
  builder.addFieldInt8(0, eventType, ToFrontend.NONE);
}

static addEvent(builder:flatbuffers.Builder, eventOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, eventOffset, 0);
}

static endToFrontendMessage(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static finishToFrontendMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset);
}

static finishSizePrefixedToFrontendMessageBuffer(builder:flatbuffers.Builder, offset:flatbuffers.Offset) {
  builder.finish(offset, undefined, true);
}

static createToFrontendMessage(builder:flatbuffers.Builder, eventType:ToFrontend, eventOffset:flatbuffers.Offset):flatbuffers.Offset {
  ToFrontendMessage.startToFrontendMessage(builder);
  ToFrontendMessage.addEventType(builder, eventType);
  ToFrontendMessage.addEvent(builder, eventOffset);
  return ToFrontendMessage.endToFrontendMessage(builder);
}
}
