// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { ConnectionStatus } from '../../discuss/ipc-protocol/connection-status.js';


export class WsConnection {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WsConnection {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWsConnection(bb:flatbuffers.ByteBuffer, obj?:WsConnection):WsConnection {
  return (obj || new WsConnection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWsConnection(bb:flatbuffers.ByteBuffer, obj?:WsConnection):WsConnection {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WsConnection()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

status():ConnectionStatus {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : ConnectionStatus.Connected;
}

static startWsConnection(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addStatus(builder:flatbuffers.Builder, status:ConnectionStatus) {
  builder.addFieldInt8(0, status, ConnectionStatus.Connected);
}

static endWsConnection(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWsConnection(builder:flatbuffers.Builder, status:ConnectionStatus):flatbuffers.Offset {
  WsConnection.startWsConnection(builder);
  WsConnection.addStatus(builder, status);
  return WsConnection.endWsConnection(builder);
}
}
