// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { IncomingMessageUnion, unionToIncomingMessageUnion, unionListToIncomingMessageUnion } from '../../discuss/ipc-protocol/incoming-message-union.js';


export class WsMessageEvent {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):WsMessageEvent {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsWsMessageEvent(bb:flatbuffers.ByteBuffer, obj?:WsMessageEvent):WsMessageEvent {
  return (obj || new WsMessageEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsWsMessageEvent(bb:flatbuffers.ByteBuffer, obj?:WsMessageEvent):WsMessageEvent {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new WsMessageEvent()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

messageType():IncomingMessageUnion {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : IncomingMessageUnion.NONE;
}

message<T extends flatbuffers.Table>(obj:any):any|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__union(obj, this.bb_pos + offset) : null;
}

static startWsMessageEvent(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addMessageType(builder:flatbuffers.Builder, messageType:IncomingMessageUnion) {
  builder.addFieldInt8(0, messageType, IncomingMessageUnion.NONE);
}

static addMessage(builder:flatbuffers.Builder, messageOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, messageOffset, 0);
}

static endWsMessageEvent(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createWsMessageEvent(builder:flatbuffers.Builder, messageType:IncomingMessageUnion, messageOffset:flatbuffers.Offset):flatbuffers.Offset {
  WsMessageEvent.startWsMessageEvent(builder);
  WsMessageEvent.addMessageType(builder, messageType);
  WsMessageEvent.addMessage(builder, messageOffset);
  return WsMessageEvent.endWsMessageEvent(builder);
}
}
