// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class CallState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):CallState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsCallState(bb:flatbuffers.ByteBuffer, obj?:CallState):CallState {
  return (obj || new CallState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsCallState(bb:flatbuffers.ByteBuffer, obj?:CallState):CallState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new CallState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ts():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

hasCall():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

hasState():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isMute():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isDeaf():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isCameraOn():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 14);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

isScreenOn():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 16);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startCallState(builder:flatbuffers.Builder) {
  builder.startObject(7);
}

static addTs(builder:flatbuffers.Builder, ts:bigint) {
  builder.addFieldInt64(0, ts, BigInt('0'));
}

static addHasCall(builder:flatbuffers.Builder, hasCall:boolean) {
  builder.addFieldInt8(1, +hasCall, +false);
}

static addHasState(builder:flatbuffers.Builder, hasState:boolean) {
  builder.addFieldInt8(2, +hasState, +false);
}

static addIsMute(builder:flatbuffers.Builder, isMute:boolean) {
  builder.addFieldInt8(3, +isMute, +false);
}

static addIsDeaf(builder:flatbuffers.Builder, isDeaf:boolean) {
  builder.addFieldInt8(4, +isDeaf, +false);
}

static addIsCameraOn(builder:flatbuffers.Builder, isCameraOn:boolean) {
  builder.addFieldInt8(5, +isCameraOn, +false);
}

static addIsScreenOn(builder:flatbuffers.Builder, isScreenOn:boolean) {
  builder.addFieldInt8(6, +isScreenOn, +false);
}

static endCallState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createCallState(builder:flatbuffers.Builder, ts:bigint, hasCall:boolean, hasState:boolean, isMute:boolean, isDeaf:boolean, isCameraOn:boolean, isScreenOn:boolean):flatbuffers.Offset {
  CallState.startCallState(builder);
  CallState.addTs(builder, ts);
  CallState.addHasCall(builder, hasCall);
  CallState.addHasState(builder, hasState);
  CallState.addIsMute(builder, isMute);
  CallState.addIsDeaf(builder, isDeaf);
  CallState.addIsCameraOn(builder, isCameraOn);
  CallState.addIsScreenOn(builder, isScreenOn);
  return CallState.endCallState(builder);
}
}
