// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import { CallState } from '../../discuss/ws-protocol/call-state.js';
import { Error } from '../../discuss/ws-protocol/error.js';
import { Ping } from '../../discuss/ws-protocol/ping.js';
import { Pong } from '../../discuss/ws-protocol/pong.js';
import { PttDown } from '../../discuss/ws-protocol/ptt-down.js';
import { PttUp } from '../../discuss/ws-protocol/ptt-up.js';
import { Shutdown } from '../../discuss/ws-protocol/shutdown.js';
import { Status } from '../../discuss/ws-protocol/status.js';


export enum MessageBody {
  NONE = 0,
  Ping = 1,
  Pong = 2,
  PttDown = 3,
  PttUp = 4,
  Status = 5,
  CallState = 6,
  Error = 7,
  Shutdown = 8
}

export function unionToMessageBody(
  type: MessageBody,
  accessor: (obj:CallState|Error|Ping|Pong|PttDown|PttUp|Shutdown|Status) => CallState|Error|Ping|Pong|PttDown|PttUp|Shutdown|Status|null
): CallState|Error|Ping|Pong|PttDown|PttUp|Shutdown|Status|null {
  switch(MessageBody[type]) {
    case 'NONE': return null; 
    case 'Ping': return accessor(new Ping())! as Ping;
    case 'Pong': return accessor(new Pong())! as Pong;
    case 'PttDown': return accessor(new PttDown())! as PttDown;
    case 'PttUp': return accessor(new PttUp())! as PttUp;
    case 'Status': return accessor(new Status())! as Status;
    case 'CallState': return accessor(new CallState())! as CallState;
    case 'Error': return accessor(new Error())! as Error;
    case 'Shutdown': return accessor(new Shutdown())! as Shutdown;
    default: return null;
  }
}

export function unionListToMessageBody(
  type: MessageBody, 
  accessor: (index: number, obj:CallState|Error|Ping|Pong|PttDown|PttUp|Shutdown|Status) => CallState|Error|Ping|Pong|PttDown|PttUp|Shutdown|Status|null, 
  index: number
): CallState|Error|Ping|Pong|PttDown|PttUp|Shutdown|Status|null {
  switch(MessageBody[type]) {
    case 'NONE': return null; 
    case 'Ping': return accessor(index, new Ping())! as Ping;
    case 'Pong': return accessor(index, new Pong())! as Pong;
    case 'PttDown': return accessor(index, new PttDown())! as PttDown;
    case 'PttUp': return accessor(index, new PttUp())! as PttUp;
    case 'Status': return accessor(index, new Status())! as Status;
    case 'CallState': return accessor(index, new CallState())! as CallState;
    case 'Error': return accessor(index, new Error())! as Error;
    case 'Shutdown': return accessor(index, new Shutdown())! as Shutdown;
    default: return null;
  }
}
