// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

export enum Modifier {
  Shift = 0,
  Control = 1,
  Alt = 2,
  Meta = 3
}
