// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

import { KeyBinding } from '@extension/src/discuss/ws-protocol/key-binding.js';


export class PttUp {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PttUp {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPttUp(bb:flatbuffers.ByteBuffer, obj?:PttUp):PttUp {
  return (obj || new PttUp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPttUp(bb:flatbuffers.ByteBuffer, obj?:PttUp):PttUp {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PttUp()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ts():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

key(obj?:KeyBinding):KeyBinding|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new KeyBinding()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

static startPttUp(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTs(builder:flatbuffers.Builder, ts:bigint) {
  builder.addFieldInt64(0, ts, BigInt('0'));
}

static addKey(builder:flatbuffers.Builder, keyOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, keyOffset, 0);
}

static endPttUp(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

}
