// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class PttDown {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PttDown {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPttDown(bb:flatbuffers.ByteBuffer, obj?:PttDown):PttDown {
  return (obj || new PttDown()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPttDown(bb:flatbuffers.ByteBuffer, obj?:PttDown):PttDown {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PttDown()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

ts():bigint {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readUint64(this.bb_pos + offset) : BigInt('0');
}

isRepeat():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startPttDown(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTs(builder:flatbuffers.Builder, ts:bigint) {
  builder.addFieldInt64(0, ts, BigInt('0'));
}

static addIsRepeat(builder:flatbuffers.Builder, isRepeat:boolean) {
  builder.addFieldInt8(1, +isRepeat, +false);
}

static endPttDown(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPttDown(builder:flatbuffers.Builder, ts:bigint, isRepeat:boolean):flatbuffers.Offset {
  PttDown.startPttDown(builder);
  PttDown.addTs(builder, ts);
  PttDown.addIsRepeat(builder, isRepeat);
  return PttDown.endPttDown(builder);
}
}
