// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class Shutdown {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Shutdown {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsShutdown(bb:flatbuffers.ByteBuffer, obj?:Shutdown):Shutdown {
  return (obj || new Shutdown()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsShutdown(bb:flatbuffers.ByteBuffer, obj?:Shutdown):Shutdown {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new Shutdown()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startShutdown(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endShutdown(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createShutdown(builder:flatbuffers.Builder):flatbuffers.Offset {
  Shutdown.startShutdown(builder);
  return Shutdown.endShutdown(builder);
}
}
